### ISSUE TITLE
Status Bar Overlay Overlaps Other Text

### ISSUE THREAD

**Issue by iAdam1n** [hbang/TypeStatus#47] opened 2015-03-08 18:09 UTC
This happens when switching from a white status bar background to a black one (and visa versa). Image attached below of the issue. 
![image1](https://cloud.githubusercontent.com/assets/2139641/6546920/4a472dcc-c5be-11e4-9727-c5f23463a53e.PNG)

**Comment by kirb** [comment] 2015-03-09 07:51
Duplicate of #37

**Closed by kirb** 2015-03-09 07:51 UTC
Labels: bug
